import { FuelType, Vehicle, VehicleType } from '../app/model/external/vehicle';

export const VEHICLES: Vehicle[] = [
  {
    id: 0,
    name: 'El Rusho McQueen',
    type: VehicleType.CAR,
    numberOfSeats: 2,
    isAvailable: true,
    fuelType: FuelType.DIESEL,
    deposit: 6900,
    pricePerDay: 420,
    photoUrl: 'https://i.imgur.com/P74meQD.png',
  },
  {
    id: 1,
    name: 'Audi A4',
    type: VehicleType.CAR,
    numberOfSeats: 5,
    isAvailable: true,
    fuelType: FuelType.GASOLINE,
    deposit: 1000,
    pricePerDay: 200,
    photoUrl:
      'https://imageio.forbes.com/specials-images/imageserve/5d35eacaf1176b0008974b54/2020-Chevrolet-Corvette-Stingray/0x0.jpg?format=jpg',
  },
  {
    id: 2,
    name: 'Audi A6',
    type: VehicleType.CAR,
    numberOfSeats: 5,
    isAvailable: true,
    fuelType: FuelType.GASOLINE,
    deposit: 1000,
    pricePerDay: 200,
    photoUrl: 'https://www.topgear.com/sites/default/files/2022/07/13.jpg',
  },
  {
    id: 3,
    name: 'Audi A8',
    type: VehicleType.CAR,
    numberOfSeats: 5,
    isAvailable: true,
    fuelType: FuelType.GASOLINE,
    deposit: 1000,
    pricePerDay: 200,
    photoUrl:
      'https://img.freepik.com/darmowe-zdjecie/samochod-sportowy-jadacy-po-asfaltowej-drodze-w-nocy-generatywnej-ai_188544-8052.jpg?size=626&ext=jpg&ga=GA1.1.1546980028.1703980800&semt=ais',
  },
  {
    id: 4,
    name: 'Audi Q3',
    type: VehicleType.CAR,
    numberOfSeats: 5,
    isAvailable: true,
    fuelType: FuelType.GASOLINE,
    deposit: 1000,
    pricePerDay: 200,
    photoUrl:
      'https://cdni.autocarindia.com/utils/imageresizer.ashx?n=https://cms.haymarketindia.net/model/uploads/modelimages/Lamborghini-Revuelto-190920231426.jpg',
  },
  {
    id: 5,
    name: 'Audi Q5',
    type: VehicleType.CAR,
    numberOfSeats: 5,
    isAvailable: true,
    fuelType: FuelType.GASOLINE,
    deposit: 1000,
    pricePerDay: 200,
    photoUrl:
      'https://www.autocentrum.pl/ac-file/car-version-photo/1/audi-q5-2017-2-0-tdi-190km-2017-2019-325951.jpg',
  },
  {
    id: 6,
    name: 'Tesla Model S',
    type: VehicleType.CAR,
    numberOfSeats: 5,
    isAvailable: true,
    fuelType: FuelType.ELECTRIC,
    deposit: 5000,
    pricePerDay: 500,
    photoUrl:
      'https://www.autocentrum.pl/ac-file/car-version-photo/1/audi-q5-2017-2-0-tdi-190km-2017-2019-325951.jpg',
  },
  {
    id: 7,
    name: 'Trumck',
    type: VehicleType.TRUCK,
    numberOfSeats: 2,
    isAvailable: true,
    fuelType: FuelType.DIESEL,
    deposit: 2000,
    pricePerDay: 400,
    photoUrl:
      'https://www.autocentrum.pl/ac-file/car-version-photo/1/audi-q5-2017-2-0-tdi-190km-2017-2019-325951.jpg',
  },
];
